<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>Blazorade.Bootstrap</Title>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.0.0-alpha.1</Version>
    <RepositoryUrl>https://github.com/Blazorade/Blazorade-Bootstrap</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Blazorade/Blazorade-Bootstrap/wiki</PackageProjectUrl>
    <Copyright>Copyright © 2025 Blazorade</Copyright>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazorade.Core" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.17" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
	<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
